api_version = "2024-04"

[[extensions]]
name = "t:name"
handle = "rename-customization"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.payment-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/:id"

  [extensions.input.variables]
    namespace = "$app:payment-customization"
    key = "function-configuration"